[package]
authors = ["Rick Yang <rick68@gmail.com>"]
description = "A echo server written in Rust"
license = "MPL-2.0"
name = "echo"
version = "0.1.4"
edition = "2018"

[dependencies]
ctrlc = "3.1.9"
env_logger = "0.8.3"
log = "0.4.14"
