combine_control_expr = false
edition = "2018"
fn_single_line = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
ignore = []
license_template_path = ""
imports_granularity = "Crate"
newline_style = "Native"
overflow_delimited_expr = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
report_fixme = "Always"
report_todo = "Always"
unstable_features = true
use_field_init_shorthand = true
use_try_shorthand = true
version = "Two"
wrap_comments = true
